<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WANGFAN" name="Default test" tests="8" failures="2" timestamp="25 May 2016 06:27:33 GMT" time="200.331" errors="0">
  <testcase name="test1CreatePlan" time="24.704" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
  <testcase name="test2CreateGrp" time="30.781" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
  <testcase name="test3CreateIdea" time="29.409" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
  <testcase name="test5CreateKeyByPhoenix" time="33.692" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc">
    <failure type="java.lang.AssertionError" message="新建关键词失败！
Expected: &amp;quot;B&amp;quot;
     got: &amp;quot;A&amp;quot;
">
      <![CDATA[java.lang.AssertionError: 新建关键词失败！
Expected: "B"
     got: "A"

	at org.junit.Assert.assertThat(Assert.java:780)
	at com.sogou.bizqa.seleniumxuri.action.CommonKey.createKeyByPhoenix(CommonKey.java:121)
	at com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc.test5CreateKeyByPhoenix(TestSceneCpc.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test5CreateKeyByPhoenix -->
  <testcase name="test6DeleteKey" time="13.531" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc">
    <failure type="java.lang.AssertionError" message="删除关键词失败！
Expected: &amp;quot;B&amp;quot;
     got: &amp;quot;A&amp;quot;
">
      <![CDATA[java.lang.AssertionError: 删除关键词失败！
Expected: "B"
     got: "A"

	at org.junit.Assert.assertThat(Assert.java:780)
	at com.sogou.bizqa.seleniumxuri.action.CommonKey.deleteKey(CommonKey.java:136)
	at com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc.test6DeleteKey(TestSceneCpc.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test6DeleteKey -->
  <testcase name="test7DeleteIdea" time="19.126" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
  <testcase name="test8DeleteGrp" time="22.233" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
  <testcase name="test9DeletePlan" time="19.797" classname="com.sogou.bizqa.seleniumxuri.scenario.TestSceneCpc"/>
</testsuite> <!-- Default test -->
